In [1]:
import numpy as np


In [2]:
x = np.array([0, 1, 2, 3])
x

array([0, 1, 2, 3])

In [6]:
w = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
y = np.arange(8).reshape(4, 2)
y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [18]:
x = np.array([0, 1, 2, 3])

#square each value
print(np.square(x))

#square root each value
print(np.sqrt(x))

#cosine of each value
print(np.cos(x))

#find max value
print(np.max(x))

#find min value
print(np.min(x))

#find mean of input array
print(np.mean(x))

#find standard dev. of the input array
print(np.std(x))

[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]
3
0
1.5
1.118033988749895
